### ISSUE TITLE
Add Mario Animations For Starting Position

### ISSUE THREAD

**Issue by TheJoeSmo** [TheJoeSmo/Foundry#14]
Currently, there is no way to identify the starting powerup Mario will take inside the editor.  This can lead to confusion when running this through the emulator.  Instead, the Mario's powerup should dynamically change based on the settings that determine his powerups.

**Comment by TheJoeSmo** [comment]
I forgot to mention, but this issue was suggest and recommended by @Dariosky-01 on Discord.  I have included his name as per request.

**Comment by Dariosky-01** [comment]
Let's say that I have suggested many improvements beyond this, such as the possibility of having the star and starting from a world of your choice, a useful option if you want to test a bonus level that is connected to the world in which you play, plus I think this also helps to do more, to test the levels of the sprite enemies that move in the different maps.
