### ISSUE TITLE
Broken tiles

### ISSUE THREAD

**Issue by SKJyannick** [TheJoeSmo/Foundry#145]
Underground:
30-Degree Hill & Water Pits B
Door
45 Degree Diagonal Hill Strip A
Weird 30-Degree Hill (might be broken ingame too, idk)
30 Degree Underwater Hill - Down/Right
Lower Right Hill Corner - UnderWater (the one with the noteblock graphic)
Weird 45 Degree Hill (might be broken ingame too, idk)
45 Degree Diagonal Hill Strip B
30 Degree Underwater Hill - Up/Left
Triangular Hill Object A (honestly I have no idea what this is)
Weird 45 Degree Hill (again?)
Weird 30-Degree Hill (again too?)
30 Degree Diagonal Hill Strip B
Triangular Hill Object B (same thing, no idea lol)
1 Hill Strip
30 Degree Diagonal Hill Strip A
Steps A
Steps B
30 Degree Underwater Hill - Down/Left
30 Degree Underground Hill - Down/Left (invisible)
![image](https://user-images.githubusercontent.com/59059085/146983261-4ffc7b87-8eb9-4225-851f-ef55aa0a7ee9.png)
Some tiles are only broken in the preview:
![image](https://user-images.githubusercontent.com/59059085/146984434-71b48291-77c0-406c-ac55-7caeaa2e98f0.png)

Ice:
Icy flat ground (Maybe it's broken ingame too when you try to expand it to the ground?)
Top of snowy platform
Leftward Pipe
Weird Waterfall
Bullet Bill Machine
Water (still)
Water (moves to left)
Warer (moves to right)
Bowser Castle Background (don't know if this is broken ingame too)
Weird Quicksand (don't know if this is broken ingame too)
Blue Wooden Blocks
Silver Coins (only broken in the preview)
Door (I think it has the wrong color?)
![image](https://user-images.githubusercontent.com/59059085/146984360-6e28ae7b-f5c7-47ef-b441-2d81b7d9a470.png)

If I find more, I will post them too.

**Comment by TheJoeSmo** [comment]
Fixed by 434366182625151f9b277b39eb2a6568d4969eed and 87c14bc262efaad6bd46d62bfc9ddf6a1542b828
