### ISSUE TITLE
Generator `Vine Extending Downward` Not Supported

### ISSUE THREAD

**Issue by Dariosky-01** [TheJoeSmo/Foundry#18]
The two problems are different, the first, the most important concerns the placement in the game when the level is installed and made playable in memory, essentially as you can see in the video below many of these are repeated with fixed cycles, I think every 16X of length, the other problem that can always be seen in a dedicated video is that put this in a left corner of the "Blue X-Blocks" object with 4 bytes it ceases to extend to a condition, as you can see I made three attempts , if for X-Blocks I select put in foreground or background level it remains as before, but if I do the same thing by putting something in front of X-Blocks and selecting put to background level it starts working.

https://user-images.githubusercontent.com/81451904/139574861-8c80d91a-c24d-4c4f-9fd3-a57926c3ddcc.mp4

https://user-images.githubusercontent.com/81451904/139574900-92ce45e3-469a-4aca-bb13-502c0c2c92ce.mp4

**Comment by TheJoeSmo** [comment]
Updated title to be more precise

**Comment by Dariosky-01** [comment]
I didn't understand what happened, but I don't think you need to delete a feature when it exists, at most correct it.
