### ISSUE TITLE
Possible changes to add

### ISSUE THREAD

**Issue by Dariosky-01** [TheJoeSmo/Foundry#191]
A good modification idea would be to have a new function item opens a window inside the "customize" menu (the one created by Wip) one that opens a window that allows simple editable changes by acting on points "[✓]" that given the label they can act by simply adding or removing what is written as a label in the tip, the entry should be called "miscellaneous changes" and should have a long list of changes, I have compiled a list below.
At the end I wrote other items to add to this new menu simply because they would be other changes a little more complicated than a simple inclusion or exclusion with a simple tip, therefore very deserving of a completely customized item.

Here is the list of the window that can be activated from the item: "Miscellaneous changes"

1) Activate or deactivate the card game
2) Munchers don't change
3) Add deadly block to the Ship set
4) Mario moves after killing boom boom
5) Goombas can be squashed in water
6) Disable Mario spinning with the star
7) Disable the "current world" notification window
8) Reset the large demand switches at the level exit.

These may be other changes they can fit perfectly inside the menu but inside a different item that uses a multipurpose window for multiple changes, one uses a setting and that changes according to which change is chosen inside with choices through a distinct choice means example:
"
1 (o)
2 (    )
3 (    )
"
and a unique regulator for each option chosen, as I said

"- | -------"

This is the second list of the second item in the menu, called:
"customize various settings"

1) decide the amount of shots needed to kill the enemies
2) Decide what Mario's fire power is worth
3) Adjust the speed of enemies in the level
4) Adjust how many shots of fire a hammer blow is worth
5) Increase the duration of the main star
6) Increases the duration of the super power to fly
7) Increase the ability to attribute super speed
8) Adjust the time of the superpower obtained
9) Adjust the speed of the map sprites

We could put as many items in the menu as there are below using a basic window with maximum tabs where after these are filled with the data that you choose according to the choices written below, the name of the item in the menu should be "Change environment of the game"

list:

1) Change the general colors of the game
(of the outer bar in the map, colors for each graphic set, colors of Mario's flashing with the star, colors of Mario's suits
2) Modify the structure of the bar and frame of the map area (with a simple internal modification using typical applicable models and previewing the result)
3) Modification of the mushroom house environment (with models and preview as mentioned in point 2)
4) Modification of environment, cards and various modifications of the "card game"
5) Set the increment to get to super

6) Decide which sequence of worlds to appear 
1 *

{
1*=
This change comes from an old idea that came to me once in a while but to which no one has ever thought of adding, in practice it would be a GUI, (a window) that allows you to choose which world to start from, how many worlds to play in total and in what sequence they must present themselves to each world passed, for this I had come up with a hypothesis on how to manage a simple GUI in case of realization, where simply simple changes were applied to a window that contained 8 drop-down menus in series for each row representing the worlds originals to imitate the original sequence in the reading of each line, with inside the list of all the worlds expressed simply with the word "world" followed by a number from 1 to 8 for each world and 8 selections "points [✔] "next to these menus for activating and deactivating those precise worlds in succession, thus being able to deactivate some of them and put some of them before or after the original succesion, m and therefore also make sure that if you get there via world 9 with a whistle inside one of those disabled worlds, the world following the disabled one would still be one of those chosen in the custom sequence.

it should look like this:

--------------------------------- x
Change the sequence of the game worlds:

Sequence: Use:
1- [World 1 [v]]; [x]
2- [World 2 [v]]; [✓]
3- [World 3 [v]]; [x]
4- [World 4 [v]]; [✓]
5- [World 5 [v]]; [✓]
6- [World 6 [v]]; [x]
7- [World 7 [v]]; [x]
8- [World 8 [v]]; [✓]
----------------------------------

I think there would be only one last problem, manage the number in the "current world notification" window that appears when opening the game, and in the status bar of both the map and the levels inside the map of in a world, well nothing simpler , each time the sequence is confirmed the number relative to each world of the selected active sequence changes, in the case of the deactivated worlds they could all be named as world "0"
}

The rest of the following changes are changes I think they should be right in the menu because I think they really deserve a custom window.

1) Decide on the gifts of the princess
2) Customize after how many points the card game appears

**Comment by TheJoeSmo** [comment]
This issue is a feature request.  No one able to implement this feature has backed this claim.  Until this feature is backed by a developer, it will remain closed.
