### ISSUE TITLE
An advanced way of editing TSA within the "view blocks" window.

### ISSUE THREAD

**Issue by Dariosky-01** [TheJoeSmo/Foundry#195]
Greetings

I have some good ideas for improvement for the "view blocks" feature
That will allow a better way of editing, very different TSA editor which is what this function wants to imitate.
I start from the fact that currently it should not open a window at each selection of the object to be changed to show the object to be changed in a different window because this clutters the screen a lot, it is fine in the same window where you see one of the selected banks with all the tile designs are part of it.
I made some screenshots and some drawings above to make it clear what my specific idea is.

![IMG_20220421_145403](https://user-images.githubusercontent.com/81451904/164473404-b751036e-cfc4-4ca8-b675-15855d7f36e4.png)

In the first window when opening the "view blocks" function in my drawn screenshot you see a red frame with four yellow frames inside, the red represents the area of ​​the object to be modified, the image that always appears in a separate window after a click on a tile, the four yellow frames would obviously be the four tiles making up one of the tiles.
Below in the drawing you see another frame, one green, that should show the selected tile, one of those are part of the red frame, then one of the four yellow ones.
To open the patterns window, the one where a sample tile is actually selected, just click inside the green frame, which always takes into account the current selection, the one stored in memory and chosen by the user.
There are two black rectangles and one blue, I will tell later what they are for.

Entering the "patterns" window this should have three things higher than the two zoom buttons (in and out), arrows and a "8 * 16 spites" display mode to choose for orientation, it is a feature already present in the PPU functionality of FCEUX.

![IMG_20220421_143040](https://user-images.githubusercontent.com/81451904/164473522-117c9939-ccd9-4fb2-9e01-57e1653285a0.png)

![IMG_20220421_142845](https://user-images.githubusercontent.com/81451904/164473638-b036ad4f-5f82-4aba-be09-9f76b804cd68.png)

![IMG_20220421_134049](https://user-images.githubusercontent.com/81451904/164473673-c0357285-b557-4561-9f9e-6f48194e7409.png)

The arrows in there is what actually makes this system change a lot compared to the traditional TSA Editor.

![IMG_20220421_155831](https://user-images.githubusercontent.com/81451904/164474535-0d0a0bd5-74f4-417b-8f27-280ddccde177.png)

The arrows should be able to change the different patterns so that you can access the other patterns (the ones you see by selecting out other banks) where currently it is not possible to access because these arrows are missing for the change.
Both the patterns window and the one that displays blocks inside the desk should have colored selection frames that move with a click of the left mouse button (inside the different areas of card selection or pattern selection) and with two clicks selecting definitively, really choosing .

I am coming up with an extra idea to need right now, maybe the patterns window could show the tile that is shown outside in the window displays blocks in the "red frame" area (the one I drew) so, together with the framed selection of each single tile yes could see a preview of the choice without having to select necessarily to see, only afterwards, the result out, thus always seeing one of those four parts of the chosen tile change as a preview, but in the interested part, meaning seeing three static tiles in the image and a dynamic, that choice outside and that changes according to where the frame that I proposed before would be moved with single clicks of the mouse was always used for a selection (it serves to orientate).

Exiting and returning to those two black and one blue strips inside the window displays blocks, they are buttons, where two are the same, and they both serve to do a simple thing.
The black buttons, depending on which one you choose if above or below, should open a new window that serves only to modify the current drawing, nothing too demanding, in practice opening the first one at the top would show the same window that currently, in the current version Foundry opens by selecting a counter tile, but underneath this it should have four zones to select the predefined colors used, to be able to choose them and use as a means of editing just a pencil and a paint bucket, nothing else.
The other blue button outside, returning to the display blocks window, would only have the task of applying the chosen model and in case modified by hand inside one of those four areas selected and marked by me with the yellow frames, because when a design would be chosen inside the window patterns it should not be applied immediately but there should be a confirmation outside, in the window displays blocks, obviously you could also modify this small part with the black button it leads to a modification of the design, after if you like you press the blue button (apply ) otherwise just touch the original part to make it go back as before (one of those four yellow frames selected previously).

**Comment by Dariosky-01** [comment]
Maybe it was better I immediately explained why ...

Well, I can tell you the reasons, let's talk about the 8 * 16 function.

The only reason for this is to orient yourself, but it seems to me I had already written it even if I'm not sure, why to orient yourself? Because the objects lining up as they should be can be easily identified, and if one looks for a piece of a game object he finds it immediately, you know it's not easy sometimes to find some pieces, you get confused with some objects, and often if you use this system it's because you want to change an object into an object that exists elsewhere and then you need all four pieces, which is easy to distinguish if you have the 8 * 16 mode.

**Comment by Dariosky-01** [comment]
For the other point the reason is simple, because I wanted to reserve an extra window only in the case of a manual pixel modification, a kind of bland functionality of YY-CHR with those black buttons I showed with a black rectangle, they serve just to that, to open a window with 4 colors, those used by the object, and two selection buttons one for a pencil and one for a bucket.
There are two black buttons because one would act on a tile, and one on the selected model.
I just wanted to reserve an extra window for a different functionality.

It seems you didn't immediately guess ...
Well just reread and pay a little more attention, I hope you understand what the blue button or the green frame part is for, right?
(the frames are points represented to make the idea understood)

**Comment by TheJoeSmo** [comment]
We should make issues to solve problems that do not exist at the current moment.  Because there does not exist a manual pixel editor, your point is mute.  If a manual pixel editor exists in the future, this issue could be reopened.
