### ISSUE TITLE
New tool in the "view" menu: Enemy action area

### ISSUE THREAD

**Issue by Dariosky-01** [TheJoeSmo/Foundry#197]
Salutations

As written in the title, this publication aims to point out that it is currently impossible to visualize the dangerous areas for Mario and the airs where the memics of the game act.

I believe this tool is essential for three aspects during the level modification work:

1-
It allows the user to calculate where the enemies reach maximum and to calculate the objects of the level as he must order them so that he understands the level of difficulty during the game or whether or not it is impossible or an exaggeratedly difficult way that setting between the presence of objects and enemies set a certain way.

2-
It allows those who want to use many enemies in a limited area to establish how many enemies act on a level area taken as a sample (in the horizontal direction of blocks x, area loaded into memory during the execution of the game and scrolling of the level ) to prevent the game from slowing down due to the excessive presence of enemies in a small area.

3-
Based on the calculation mentioned in point .2 to calculate the presence of the enemies as far as they arrive to allow to avoid display errors of the enemies in the event that, of the total enemies used in the level there are enemies that are not compatible with each other that causes this problem, because the best way to use enemies of incompatible groups is to use them far apart so that they do not come into contact in the same area that the game is showing in the video output and in any case a little further back and further forward area made available in the background.

I understand it's a bit complicated but it serves.
It can be complicated to calculate some enemies but except for someone who follows the course of the floor and therefore cannot be calculated (at least perhaps with a lot of work) the others are "easy" to implement (it is still quite a big job because there are so many enemies).

**Comment by TheJoeSmo** [comment]
This issue is a feature request.  No one able to implement this feature has backed this claim.  Until this feature is backed by a developer, it will remain closed.
