### ISSUE TITLE
A new main function

### ISSUE THREAD

**Issue by Dariosky-01** [TheJoeSmo/Foundry#198]
Hi I had an idea about managing software primarily because I often found myself using multiple open Foundry software to look at one thing and be able to copy something into the other.

At this point, to avoid the inconvenience of opening more software and still waiting a long time, you could do as follows.

As happens in the best software you could dedicate a worksheet, the sheet should represent a loaded layer, and therefore these worksheets could be more loaded layers to manage.
This should work just like an internet browser works with web pages open, where you can ask for some while still leaving the browser open, so there should be a tab management bar in the editor, as if they were web pages containing spreadsheets. representing the levels.
As in browsers, however, you should be able to detach them from the bar containing them, in other words you should be able to detach the tabs
contain the open game levels or empty level pages if we add the new tab "[+]" functionality, and if outside the bar it contains the tabs they should assume the similarity with simple windows, where already from there you should be able to choose whether to close them , and then if the layers are not saved, ask whether to save, and have another button for the automatic indentation of the tab in its bar from where it was detached.
I think the bar is adequate under the buttons are at the top, those under the menu.

**Comment by TheJoeSmo** [comment]
This issue is a feature request.  No one able to implement this feature has backed this claim.  Until this feature is backed by a developer, it will remain closed.
