### ISSUE TITLE
Some problems related to the palette window to be solved

### ISSUE THREAD

**Issue by Dariosky-01** [TheJoeSmo/Foundry#20]
A little while ago I tried to change some colors in the level but when I tried to put "level reload" action that I often do to delete the last actions done, the colors there in the window have remained, they have not updated returning to what they were before in memory.
It needs to be resolved.
However, I noticed that that part is large enough to accommodate a second palette, since this is the telative one, the one dedicated to enemies could be added to the background.

![K](https://user-images.githubusercontent.com/81451904/139579706-dee0be8b-8210-40c4-b6cd-915226ea393b.PNG)

Opening with a click of the pointer in one of the colors opens a window for the color change, for the choice, it would be more useful to see a preview while scrolling the pointer over the colors so that it is not essential, if you are very undecided, to set for then return if you are not sure, it would be enough just to scroll over the pointer to see the color applied and when you have decided on the result you can already see there (during the window open for the change) click a color to confirm and close the small window , this would save you the hassle of opening and closing multiple times.

Another thing that could avoid the hassle of returning would be to enter a color and select others from them as if you already had the window out there, the only difference would be that from there you could think of adding labels to immediately understand what a color to avoid understanding it by making comparisons with what you see out of necessity, moreover if you decide to put the palette of the enemy sprites you could think of adding a card, then allocate two to switch to the other always for each color the title that makes it clear what it is dedicated to and under all the colors to choose from.

One thing I forgot to add even in the speech (I'm updating now) is that I have not at all advised to leave two buttons, one for the background palette and one for the sprite palette because I wanted to recommend another nice and simple function, the I change color with the mouse pointer and mouse wheel, I mean that even if there is no label and you already know where the color will act, you could make it so that when the mouse pointer points to one of the colors, without clicking to enter the internal window, it could scroll the colors in succession one after the other by making up and down with the wheel, and with each click of the wheel set the color, and if you right click in that color just canbiato returns to how it was originally.

It would not be bad to be able to see the color value inside the window, because at least if you look for value also as a form of reminder when using FCEUX it can be displayed, it can also serve because some monitors can deceive the eye but what is written you cannot be fooled.

**Comment by Dariosky-01** [comment]
I have updated the publication.

**Comment by TheJoeSmo** [comment]
Closed by #82
