### ISSUE TITLE
Small update problem when the file you are working on with Foundry open is modified externally by other software.

### ISSUE THREAD

**Issue by Dariosky-01** [TheJoeSmo/Foundry#21]
As you can understand from the title, there is a need to add an internal file update feature to Foundry when outside you are already sure that the file you are working on has changed, this should work so that it updates the file as it is out when it is changed but at the same time keeps the changes on a layer you are editing without needing to open it, then enter the layer selection window to start that change over.

If it is possible, this functionality could be in two places, one in the GUI with an icon that globally recognizes itself as "refresh" (two arrows follow each other attract to an invisible circle) and the other could be in the menu in 
"Level > *Update file Nes* "
which could therefore be close to "Select Level" and "Reload Level", I would put it under "Reload Level".

**Comment by TheJoeSmo** [comment]
This is a copy of #5  Please move discourse to that pull request.
