### ISSUE TITLE
A new search feature

### ISSUE THREAD

**Issue by Dariosky-01** [TheJoeSmo/Foundry#210]
Salutations

It would be useful to have a search function, which can be activated via the view menu, which opens a small internal window at the bottom, where it has only a white strip for entering the writing via the keyboard, what is written there automatically, even by writing a single letter it should create a tab in the left window titled "search" which displays all the icons representing objects and enemies starting with that single character entered, because everything should work automatically.
This should help the search knowing the name, in case new languages ​​are installed everything will be even easier.
Along with the favorite features that I talked about in another publication, it should help speed up the process of personalization of the moment as well.
What you need beyond the entry bar are three points "[✓]"
which could be present either on the left of this window or on the dynamic window I mentioned in another publication (perhaps only if in "advanced" mode) and which should help you understand which groups to look for:
1)
If in the object group
2)
If in the group enemies
3)
If all enemy groups are included
(ignoring the choice given in the menu item "view": "groups of enemies" mentioned in another publication, to include all enemies even with a setting previously defined there by the user)

**Comment by TheJoeSmo** [comment]
Searching is too vague of a concept.  By which way should this work?  Should this be via a fuzzy search or absolute?  How should this consider other languages?  For a search to be considered, a clear algorithm should be considered, and a preferably a library to do such a task.

**Comment by Dariosky-01** [comment]
I don't know what you mean by fuzzy or absolute search, but I gave an example, the example meant that if I write "a" in the search area, the system should find all objects that contain "a" in the first letter of the name, name that can be different according to the set language, therefore not considering English if another language is set.
So if the user writes a letter in the search, the system will have to show in the form, after creating it, all the objects and enemies that begin with that letter, if there are two letters, all those in the name that contain those two letters entered in the bar search in that written sequence.
Each special character or number should be considered separate, considering that special character or number in the whole name string.

(given the publication # 211 of the "mask" functionality I mentioned which can be activated in the "view" menu, enter a number in this search bar we are talking about and associate those numbers I mentioned in that publication where I specifically say that the masks should be numbers above the icons of objects and enemies that have identical figures, not a bad idea) *

I want to remind you that this system must take into account the filters mentioned in this publication because it speeds up the search process.
In the bar for simplicity there could be a button instead of "[✓]" points and inside a window for the choice of filters (with the "[✓]" spikes).

**Comment by TheJoeSmo** [comment]
This issue is a feature request.  No one able to implement this feature has backed this claim.  Until this feature is backed by a developer, it will remain closed.
