### ISSUE TITLE
A new function to change the addresses of colors associated with objects

### ISSUE THREAD

**Issue by Dariosky-01** [TheJoeSmo/Foundry#218]
Hello everybody

I thought it would be good to have a new function inside Foundry to facilitate an action as it would be complicated to implement with the game's hex code or through assembly functions.
This new function should basically help the user decide which color address to choose by associating another color address association with an existing one for one of the four colors used by a game object because sometimes, when you change colors, you are bound by colors that are unfortunately secured to other objects and that for this reason bind the user to choose colors that are not beautiful or normal for certain objects that must necessarily be inside that graphic set and a level created by the user.
I don't think you can have a color for everything by meaning a specific address for each part of an object, perhaps in the future it might be possible but keeping your feet on the ground and talking about what is relevant now with the reality of the facts I would say that the in this case the user should have mastered, with this new function, its possibilities being able to exchange these few color addresses as he sees fit for its modification.
Given the limitation, I think we should be able to have an edit function, to be chosen from the Foundry menu that opens an edit window to help the user deal with this editing path, where inside, at the top left of this window there is a drop-down menu where to select the objects of the game, under the object should appear, an image of the large object as seen with yy-chr in the right part when yy-chr is set so as to show an entire object in the area image editing. It would be good for object name display that the drop-down menu for object selection is as wide as the full length (horizontally) takes the image of the object to be displayed in large as seen in yy-chr. At the top a little further to the right of the menu there should be a button for changing the color combination, where the colors are groups of four predefined colors for the vision of the object, colors not that would not be real but used only for this purpose of modification, to mean the zones currently used by those colors (for the mental association of the zones used in the design of an object), below, four squares with the colors of one of the predefined combinations chosen by the user put in series one after the other below leaving a little space between them to separate them well, so meaning placed in a row one after the other (single file) vertically, after next to the right of these colors there should be a letter that cannot be modified by the user but can be modified only from the software that changes according to what the Foundry software reads from the rom.

These letters should be as many as there are currently editable colors in the Object Palette in Foundry.

I don't know why the first four colors placed in a vertical row in the palette of objects change all four together when you change one, I don't know if it is a matter of fact that there are four they do the same thing but if it has a why it wants say they are separable so the letters in total, for the object palette, should be 16 otherwise 13, but I'm sure they will be 16.

If there are 16 colors that the user actually has available, the letters that should be managed by Foundry for the associations would be those ranging from A to R.

These letters should appear in the window as I said before (and to the right of the colors to understand which area of ​​the object design a letter is associated with) according to the registered association they have in the game code.

The user at this point should have the opportunity to choose which association with the letters to do for each object, for example the water could have the opposite association to that of the color of the pieces of the hills in the graphic set "hilly" and it could be done by swapping the letters, this is just a small example but the user can very well use all the possible associations exist of each object in the game.

The user should be able to swap these four letters using a small drop-down menu, to the right of the letters written automatically by the software, to modify each of these four letters intended by the software, letters written after these four colors.
what I remember would be placed one above the other representing the non-real colors would be seen inside the drawing in large place on the left that shows the object selected by the user in large.
Each of these four small drop-down menus that can be modified by the user, inside, should obviously have all the letters going from A to R to allow the user the choice that best suits his needs and which represent associations (precise and distinct addresses to assign to a color).
To the right of each of these drop-down menus, for the customization of the object by the user with a letter to choose, there should be a simple button showing the original association as in the vanilla game code to allow reordering of the original values of the game.

You could think of doing the same thing for the colors of the sprites inside the same window without another entry in the main menu of Foundry dedicated to the color associations of the different enemies, this should be done but you should take into account that, given there would be another 16 colors in addition to the 16 letters mentioned above for the associations of the addresses of the colors of the objects and the letters of the alphabet are less than 32 then, since in any case a distinction should be made to help those who are going to program the Foundry software. a menu another drop-down menu or two buttons to change a selection between sprite list and object list, and to help the programmer, instead of just having Foundry use a letter to show the registered association, it could have "1-" written first of each letter or "2-" depending on which group of letters you are working with, both for the user in the GUI and for the programmer so as not to get confused in mod or that "1-" is the group of letters for the color associations concerning the objects and "2-" to refer to the group of color associations of the sprites.

In the drop-down menu that says "object list" or "sprite list" for the choice of which group to use it could also be written "1-" or "2-" like this:
"1- List of objects"
"2- Sprite list"

Now there is a certain difficulty of mental association for the user for him to understand which square of the palette each letter coincides with, so I think it would be appropriate that there is a drawing on the right inside the window with a drawing of a grid made of 16 squares (4x4 ) with the letters written inside, to make the user understand that the letter is the area of ​​the palette, and the sense of the succession of the letters is how we Westerners write, from left to right and then in the line below, that is, not like the Orientals who write from the top down also or like the Middle Easterners from right to left and then to the top (like Arabs) but the letters follow each other from left to right and then always in the next line.

Obviously you need a button to cancel the changes and a confirmation button that says "cancel" and "apply".

In the user's choice on the letter it is logical that all the letters must be inside each of the drop-down menus to set the one you want but, taking into consideration one of the four drop-down menus, if the user chooses a letter already used in the others three modification zones then they should swap places automatically, if for example in the first at the top I have "A" and in the fourth at the bottom I also select "A" since they cannot have the same address they should swap automatically.
Not having the software do this action automatically means for the user to have limitations that force him to do stupid actions due to constraints equivalent to design errors.

**Comment by Dariosky-01** [comment]
I just wanted to say that I considered in the speech to use the alphabet meaning the Italian one, meaning without the differences with the English one, it is obvious that you can very well interpret the 16 points of the palette to be changed as the letters go from "A" to "P" instead of from "A" to "R".

**Comment by TheJoeSmo** [comment]
This issue is a feature request.  No one able to implement this feature has backed this claim.  Until this feature is backed by a developer, it will remain closed.
