### ISSUE TITLE
New possible future help guide features in the level.

### ISSUE THREAD

**Issue by Dariosky-01** [TheJoeSmo/Foundry#64]
You might think about adding two limit display functions to simply help out SMB3 editors.
There is already the option to display the jump zones to change the level, seeing the zones with a plane hatch, with minuscule oblique lines nearby to make a hatch, what I propose is to simply make horizontal lines throughout the level from 1 pixel with a green color, a line with a linear hatch ("_ _ _ _") to help visualize the exit points of the pipes set, a simple system to visualize the mandatory heights to be respected to position the pipes "can 't go "where Mario will come out from.

Another linear function could help is that limit with two simple lines, I would do it in blue but always with a linear hatch, to highlight the upper limit if starting from the level from the bottom, and low limit, if starting from the top , they are in height "11 Y" starting from the top (zero including therefore 12) and the same from the bottom up.

Another useful limit could be the one to respect if you don't want to cause a display error, a sudden video shift, when you want to put the "Double-ended Vertical Pipe" tube object in the layer.
Often when used if it is not set to respect certain start heights in the high pipe part, and only if they are not set in the level within the GUI options in the "Edit Level Header" options in the "Scroll Directin" part the options :
[1] "Loked 'By Start Coordinates'?";
[2] "Shouldn't Appear In Game, Do Not Use." It happens that if the high part of the tube does not reach height "7 Y" but for example "11 Y" you see the video move up to bring the video to hook that high pipe point ("pipe mouth") up to a number of "Vertical Y Blocks equal to 5" this causes a sudden and fast movement of the game video frame, it is a problem it does not happen only if one of those two options.
So this functionality could only be available if one of those two options in the GUI, by placing a simple yellow line help a in the level "7 Y",
Another black hatch could be useful only if one of those two options are active and you want to highlight the part where Mario falls over and dies, this line would be dashed in black.

Since in this case, if you want to take this development path, it would be right to put another distinct menu in Foundry but only so as not to make the list of items appear exaggeratedly long in the "View" menu.

An interesting name idea as a new menu alongside the current "View" menu could be "Guidelines"

**Comment by TheJoeSmo** [comment]
I do think the idea of guides could be a very useful feature for Foundry.  But, as for the way you have described this issue, you have provided very specific cases for contributors to sustain inside the repository.  I believe this manner of solving such a solution is ineffective.  There will always be more use of guides.  Nor do I feel I can predict what you want to use them for effectively.  Due this reason, I feel the use of guides could be useful, but they must be created by you the user.  Any other mechanism of creation I am against.  For this reason, I am closing this issue.  But, if you feel strongly about the use of guides and believe they will be beneficial, I recommend creating a new issue that focuses on user created guides instead.
