### ISSUE TITLE
Scift functionality + arrow to add to selection

### ISSUE THREAD

**Issue by Dariosky-01** [TheJoeSmo/Foundry#76]
You need the function add Scift + arrow (down or up) which allows you to select one by one in a list list, such as the list in the right window, scrolling the objects in the list one after the other, keeping all those hooked in the selection from which we started, if for example I click on the first label of the list in the right window, and keep Scift taking the text of the "down arrow" one step at a time, I would see the first label hooked into the selection and then the second, then the third and all the others if I would continue to press the "down arrow" key the same should be done in the opposite direction starting from the bottom not necessarily from the last, as in the opposite version not necessarily from the first if down.
This function is typical in a Windows environment inside folders when the view is list or detailed, even in a writing software this function allows you to select a word letter by letter until you select an entire word or phrase or more, it just doesn't work in Foundry on that list and it should work like that.

**Comment by TheJoeSmo** [comment]
Closed by #91
