### ISSUE TITLE
Simple internal window problems to solve

### ISSUE THREAD

**Issue by Dariosky-01** [TheJoeSmo/Foundry#80]
Inner windows when detaching show docking dots for selection with pointer on left side of each small window, it's a wrong way to view this part, it should be on top this part.

There are scroll bars that do not show the attachment point to be able to move them, they need to be visible, and possibly larger because they are difficult to attach with the point, you must be very precise and given the point where it is not immediately detected you can hook it with the mouse pointer wastes time.

**Comment by TheJoeSmo** [comment]
The detaching dots are dependent on the internal GUI style sheets we applied.  They are very hard to change and I have no intention of messing with them.  Such problems are just part of the PySide6 framework.
